services:
  - type: web
    name: no-code-ml-pipeline-builder
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 1 -k a2wsgi.ASGIWrapper --bind 0.0.0.0:$PORT
